### ISSUE TITLE
How could I pull in stock from Snipcart

### ISSUE THREAD

**Issue by cmarabate** [snipcart/stackbit-theme-planty#11]
I was hoping you might be able to help me figure out how to have this site pull in the current stock of each product from SnipCart.

I contacted them for help but all they were able to tell me was the following...

> Stock of a product can't be retrieved in JavaScript directly with our SDK. Some of our customers don't want this information to be public, so we decided to keep it available only from our private API.
> 
> You can access this private API with a secret API key that you can generate in the dashboard, the endpoint you'll need is: GET /products/{id} documented here: https://docs.snipcart.com/v3/api-reference/products
> 
> You will need to create a Netlify function that will act as a proxy between our API and your frontend, because you should never expose your secret API key directly on the frontend.

I have created a secret API key within the Test environment in my Snipcart Dashboard and I added it as a Netlify Enviroment Variable to ensure it is not exposed to the public. But I don't understand API's well enough to know what I am supposed to do with it or how to use that endpoint that they mentioned to achieve my goal. I have spent days trying to figure APIs out and I just cannot grasp it for some reason.

So I figured you would be the person who might be able to help me since you created the site and you might already have a lot of the API work done for me and I have been raking my brain over something you already implemented and I just need to learn how to use.

I'm sorry about posting it as an issue, I will close it right away regardless what your response is. I just wanted to see if you might be able to help guide me in the right direction.

All I really need is a way for my site to be able to know if a product is out of stock and if it is to change the button to say something like "Special Order" instead of "Add to cart". But I would also be nice if it could display the current number in stock on the site as well.

Thanks,

Chris

**Comment by JeanSebTr** [comment]
Hi @cmarabate !

This repo is managed by the same team that replies to support 😉 

We've created a small intro to API on our blog if that can help: https://snipcart.com/blog/apis-integration-usage-benefits

What you could do is to expose the value through a Netlify function. Being server-side, it can use private API Keys and retrieve the data form our Rest API. Using a library like axios could be a good start. Also, using Postman to test your queries.

Apart from this, learning resources for programming and Google will be your friends in this.  Don't hesitate to reach out on support again once you've learned the missing bits if you have specific questions on our API or authentication.

**Comment by cmarabate** [comment]
> This repo is managed by the same team that replies to support 😉

Haha, that is good to know. 😳

> We've created a small intro to API on our blog if that can help: snipcart.com/blog/apis-integration-usage-benefits

Yeah your support team told me that as well lol and I had been trying to figure it out the past 2 days while dealing with being sick from the corona virus and it was not working and I couldn't figure out why. But this morning I managed to get it to work using my secret API key I created in my Snipcart Test Dashboard. I swear I tried that same key before and it didn't work but maybe I was doing something else wrong at that point. But now that I have that working maybee I will be able to figure out how to accomplish my goal. Thanks!

> What you could do is to expose the value through a Netlify function. Being server-side, it can use private API Keys and retrieve the data form our Rest API. Using a library like axios could be a good start. Also, using Postman to test your queries.

I know how to create a Environment Variable inside of Netlify. But I was thinking that all I would need to do is replace the API key in my _config.yaml file like this...
![image](https://user-images.githubusercontent.com/12236062/80234085-8adef180-8625-11ea-8ea1-611a321574a3.png)

And then I would be able to somehow be able to pull in the stock of each item from Snipcart into my site. Is that not correct?  Are you saying that I would also need to install something like axios on my site as well?

This is what you were referring too right?...
[https://github.com/axios/axios](https://github.com/axios/axios)

> Apart from this, learning resources for programming and Google will be your friends in this. Don't hesitate to reach out on support again once you've learned the missing bits if you have specific questions on our API or authentication.

Will do, I think I am getting closer at-least.


Thanks again!

**Comment by JeanSebTr** [comment]
Hi @cmarabate 
> But I was thinking that all I would need to do is replace the API key in my _config.yaml file like this...
> ![image](https://user-images.githubusercontent.com/12236062/80234085-8adef180-8625-11ea-8ea1-611a321574a3.png)

Never expose a "Secret" API Key on your website. This advice is valid for other services as well 🙂 

Public API Keys are meant to be shared or used on a website because they only allow a subset of operations that can't cause damage to an account.

Snipcart's secret keys can however perform any action on your account. But won't work with the cart on your website.

You have to call our Rest API from the backend of your website. since you're using Netlify, you can use their Functions: https://www.netlify.com/products/functions/

> This is what you were referring too right?...
> https://github.com/axios/axios

Yes. But any lib that allows making Rest requests will do.

**Comment by cmarabate** [comment]
Thanks again, I will look into Netlify functions and how to use lib tomorrow when I get some time.

But I have a quick question about something you said...

> Never expose a "Secret" API Key on your website. This advice is valid for other services as well

I know that, which is why I am using a Environment Variable. In my screenshot, SNIPCART_SECRET_API_KEY is the name of the Enviroment Variable. The value of the variable(The actual Snipcart secret API key) is not anywhere within the code of my site. It can only be accessed from within my Netlify account.

Are you saying that I shouldn't be doing it that way and should be using a Netlify function instead or did you misunderstand my screenshot and think I was just using SNIPCART_SECRET_API_KEY as a placeholder to not expose the key in my screenshot?

I've also created .env files in the past to create environment variables and made sure to include it in my .gitignore file to ensure the .env file never get committed to my repo. I that also a bad idea?

I thought that was the way I was supposed to do it.

**Comment by JeanSebTr** [comment]
Hi @cmarabate 

Using Netlify's environment variables for secrets is perfect.

However, you seem to be using the Secret API Key in place of the Public one in your website. This is what must not be done.

**Comment by cmarabate** [comment]
> Using Netlify's environment variables for secrets is perfect.

Cool, that is what I thought.

> However, you seem to be using the Secret API Key in place of the Public one in your website. This is what must not be done.

But I thought you said that I needed to use the Secret API Key in order to have the website pull in the stock of each item... What am I supposed to do with the Secret API key if I can't use it anywhere in my site? I thought that pulling it in through an environment variable was what I was supposed to do but now I am confused again.

**Comment by JeanSebTr** [comment]
Both key should be used for different purposes.

The Public API Key is the one to use for the cart on your website:
- the one to use as `data-api-key`, so it should still be in your _config.yaml
- it will be used in the frontend

 The secret one is only for the Rest API, it's the one that should be used in a Netlify function or equivalent

**Comment by cmarabate** [comment]
Okay, thanks for clarifying that for me.

So it sounds like I can use my Netlify Enviroment Variable for the Secret API key but I have to use it in addition to the Public API Key. That makes sense, I was thinking I had to use the Secret Key instead of the Public key.

Thanks again!
