### ISSUE TITLE
Cart not persisting between pages

### ISSUE THREAD

**Issue by xAurai** [snipcart/stackbit-theme-planty#2]
On the demo, the cart does not persist between pages. If you go to a product page, add to cart then go back to a category page, the cart is emptied.

For example.

[https://stackbit-theme-planty.netlify.com/products/plant1/#/](https://stackbit-theme-planty.netlify.com/products/plant1/#/) Adding products here, then navigating to [https://stackbit-theme-planty.netlify.com/store/#/](https://stackbit-theme-planty.netlify.com/store/#/) empties the cart. Navigatingback to the page [https://stackbit-theme-planty.netlify.com/products/plant1/#/](https://stackbit-theme-planty.netlify.com/products/plant1/#/) retains the cart made on that page.

No errors in the console, tested on Chrome and Edge.

**Comment by thatfrankdev** [comment]
Thanks for reporting this @xAurai. There's definitely a problem there

**Comment by thatfrankdev** [comment]
A fix for cookie expiration in our internal SDK will correct this issue (once we upgrade Planty to [Snipcart v3.0.0-beta.4](https://github.com/snipcart/snipcart-v3-feedback/releases))

**Comment by JeanSebTr** [comment]
Oups – we missed that issue when we did update to Beta 4!

We've now released the stable V3.0.0 – and updated that theme – try it out 😄
