### ISSUE TITLE
Cart modal is not keyboard accessible

### ISSUE THREAD

**Issue by djmtype** [snipcart/stackbit-theme-planty#3]
When opening the Cart "page," focus still remains on the main page, the page underneath the Cart, leaving the Cart modal's contents inaccessible by keyboard.

**Comment by JeanSebTr** [comment]
Hi there,

You can leave feedback for the cart in that repo https://github.com/snipcart/snipcart-v3-feedback 😃

We've made many improvements in the last months – just updated the theme to our most recent release!
